### ISSUE TITLE
Investigate 'org.codehaus.groovy.runtime.typehandling.GroovyCastException

### ISSUE THREAD

**Issue by uthm4n** [uthm4n/morpheus-burp-plugin#1]
```
2023-08-02_12:15:23.95895 'org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '{"scan_configurations":[{"name":"Audit checks - medium active","type":"NamedConfiguration"}],"urls":["https://test-test-test.net"]}' with class 'java.lang.String' to class 'java.util.Map'
2023-08-02_12:15:24.56226 	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:404)
2023-08-02_12:15:24.56232 	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:315)
2023-08-02_12:15:24.56241 	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:243)
2023-08-02_12:15:24.56248 	at org.codehaus.groovy.reflection.CachedField.setProperty(CachedField.java:85)
2023-08-02_12:15:24.56255 	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2785)
2023-08-02_12:15:24.56260 	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3838)
2023-08-02_12:15:24.56269 	at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:217)
2023-08-02_12:15:24.56276 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:496)
2023-08-02_12:15:24.56284 	at com.morpheusdata.burp.BurpScanTaskService.executeTask(BurpScanTaskService.groovy:74)
2023-08-02_12:15:24.56287 	at com.morpheusdata.burp.BurpScanTaskService$executeTask.callCurrent(Unknown Source)
2023-08-02_12:15:24.56296 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
2023-08-02_12:15:24.56301 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
2023-08-02_12:15:24.56306 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
2023-08-02_12:15:24.56313 	at com.morpheusdata.burp.BurpScanTaskService.executeLocalTask(BurpScanTaskService.groovy:37)
2023-08-02_12:15:24.56319 	at com.morpheusdata.core.ExecutableTaskInterface$executeLocalTask.call(Unknown Source)
2023-08-02_12:15:24.56326 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
2023-08-02_12:15:24.56333 	at com.morpheusdata.core.ExecutableTaskInterface$executeLocalTask.call(Unknown Source)
2023-08-02_12:15:24.56340 	at com.morpheus.task.TaskService.executeLocalTask(TaskService.groovy:467)
2023-08-02_12:15:24.56347 	at jdk.internal.reflect.GeneratedMethodAccessor32385.invoke(Unknown Source)
2023-08-02_12:15:24.56357 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2023-08-02_12:15:24.56364 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2023-08-02_12:15:24.56371 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
2023-08-02_12:15:24.56378 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
2023-08-02_12:15:24.56386 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
2023-08-02_12:15:24.56393 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
2023-08-02_12:15:24.56401 	at com.morpheus.task.TaskService$_executeTaskInWorkflow_closure77.doCall(TaskService.groovy:1154)
2023-08-02_12:15:24.56408 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-08-02_12:15:24.56415 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2023-08-02_12:15:24.56422 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2023-08-02_12:15:24.56429 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2023-08-02_12:15:24.56436 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
2023-08-02_12:15:24.56443 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
2023-08-02_12:15:24.56450 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
2023-08-02_12:15:24.56457 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
2023-08-02_12:15:24.56464 	at groovy.lang.Closure.call(Closure.java:412)
2023-08-02_12:15:24.56471 	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
2023-08-02_12:15:24.56478 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:112)
2023-08-02_12:15:24.56485 	at com.sun.proxy.$Proxy225.apply(Unknown Source)
2023-08-02_12:15:24.56495 	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
2023-08-02_12:15:24.56502 	at io.reactivex.subjects.ReplaySubject$UnboundedReplayBuffer.replay(ReplaySubject.java:770)
2023-08-02_12:15:24.56509 	at io.reactivex.subjects.ReplaySubject.onNext(ReplaySubject.java:352)
2023-08-02_12:15:24.56516 	at org.grails.async.factory.rxjava2.RxPromise$1.onNext(RxPromise.groovy:73)
2023-08-02_12:15:24.56524 	at io.reactivex.internal.observers.DeferredScalarDisposable.complete(DeferredScalarDisposable.java:82)
2023-08-02_12:15:24.56531 	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:72)
2023-08-02_12:15:24.56538 	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
2023-08-02_12:15:24.56545 	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:67)
2023-08-02_12:15:24.56552 	at org.grails.async.factory.rxjava2.RxPromise$_closure1.doCall(RxPromise.groovy:42)
2023-08-02_12:15:24.56559 	at jdk.internal.reflect.GeneratedMethodAccessor38148.invoke(Unknown Source)
2023-08-02_12:15:24.56569 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2023-08-02_12:15:24.56573 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2023-08-02_12:15:24.56583 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
2023-08-02_12:15:24.56591 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
2023-08-02_12:15:24.56598 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
2023-08-02_12:15:24.56608 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
2023-08-02_12:15:24.56612 	at groovy.lang.Closure.call(Closure.java:412)
2023-08-02_12:15:24.56622 	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
2023-08-02_12:15:24.56629 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:112)
2023-08-02_12:15:24.56637 	at com.sun.proxy.$Proxy222.subscribe(Unknown Source)
2023-08-02_12:15:24.56644 	at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
2023-08-02_12:15:24.56651 	at io.reactivex.Single.subscribe(Single.java:3666)
2023-08-02_12:15:24.56658 	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2023-08-02_12:15:24.56665 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
2023-08-02_12:15:24.56674 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2023-08-02_12:15:24.56683 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2023-08-02_12:15:24.56692 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2023-08-02_12:15:24.56701 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
2023-08-02_12:15:24.56709 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2023-08-02_12:15:24.56718 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2023-08-02_12:15:24.56726 	at java.base/java.lang.Thread.run(Unknown Source)
2023-08-02_12:15:24.56738 null
```

**Comment by uthm4n** [comment]
Formatted disgustingly ^, I know

**Comment by uthm4n** [comment]
Work out how to convert a string to a map in groovy

**Comment by uthm4n** [comment]
Fixed in https://github.com/uthm4n/morpheus-burp-plugin/pull/2
